@host = https://localhost:7253
@contentType = application/json


POST {{host}}/api/register

{
  "userName": "customer",
  "email": "customer@estore.com",
  "password": "estorecustomer"
}


###

POST {{host}}/api/login
Content-Type: {{contentType}}

{
  "email": "admin@estore.com",
  "password": "estoreadmin"
}