@base = https://localhost:7253/api/products
@contentType = application/json
@productId = 686851c4-c9cc-4344-82d2-39760d71d7e5
@categoryId = a3e429e9-c814-492d-b4fd-13a6c8c726e
@jwtToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNmM4NTYwMS0xNmFkLTQ5NDAtYmJmOS05Mzk0ZDY5ZWU5YzciLCJqdGkiOiI0ZTViNzk1MS05NzRjLTRhZjUtYmVlYy1jNWEyZGE2MTE3OTkiLCJnaXZlbl9uYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGVzdG9yZS5jb20iLCJwZXJtaXNzaW9ucyI6Ii0xIiwiZXhwIjoxNzAyMDUwMzQxLCJpc3MiOiJFU3RvcmUuQVBJIiwiYXVkIjoiRVN0b3JlLkFQSSJ9.VF-sxLO_tYU7rwa_f-9o10lzd8qIM8QzktY54x-KD90

### Get 
GET {{base}}/{{productId}}

### List
# filters: all filters are optional, had default value 
# and are passed with the query
# SearchTerm, 
# MinPrice 
# MaxPrice
# sortColumn = { name, price }
# sortOrder = { asc, desc }
# page
# pageSize
GET {{base}}?page=1&pageSize=10

### Create
# the user must have a permission to manage the products
POST {{base}}
Authorization: {{jwtToken}}
Content-Type: {{contentType}}

{
  "items": [
    {
      "name": "string",
      "description": "string",
      "quantity": 0,
      "purchasePrice": 0,
      "customerPrice": 0,
      "currency": "string",
      "sku": "string"
    }
  ]
}

### Delete
# the user must have a permission to manage the products
DELETE {{base}}/{{productId}}
Authorization: {{jwtToken}}

### Get details
# the user must have a permission to view details
GET {{base}}/details/{{productId}}


### List details
# the user must have a permission to view details
# filters: all filters are optional, had default value, and are passed with the query
# SearchTerm, 
# MinPrice 
# MaxPrice
# MaxQuantity
# MaxQuantity
# sortColumn = {name, price, quantity }
# sortOrder = {asc, desc}
# page
# pageSize

GET {{base}}/details?page=1&pageSize=10

### List by category
# this endpoint return all the products in the provided category or any sub-category
GET {{base}}/categories/{{categoryId}}

###
POST {{base}}/{{productId}}/categories
Authorization: {{jwtToken}}
Content-Type: {{contentType}}

{
  "categoryIds": [
    "53d0da35-5be5-42d0-ae3c-d5908f08a491"
  ]
}








