@host = https://localhost:7253
@contentType = application/json

GET {{host}}/products
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNmM4NTYwMS0xNmFkLTQ5NDAtYmJmOS05Mzk0ZDY5ZWU5YzciLCJqdGkiOiI3NDU4Mjc0NS1lNTIzLTQ5OWUtYTY3Ni1jN2YwYTVmYWQ0MzgiLCJnaXZlbl9uYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGVzdG9yZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcwMTQ3ODc2OCwiaXNzIjoiRVN0b3JlLkFQSSIsImF1ZCI6IkVTdG9yZS5BUEkifQ.yA2PzVtdWOfhMPJecSUBk8TsA-oFzTHu7kjrZVlwgjY

###

POST {{host}}/api/login
Content-Type: {{contentType}}

{
  "email": "nr.ali1912@gmail.com",
  "password": "nawarali1912"
}