@host = https://localhost:7253
@contentType = application/json

GET {{host}}/products?page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNmM4NTYwMS0xNmFkLTQ5NDAtYmJmOS05Mzk0ZDY5ZWU5YzciLCJqdGkiOiJhMGZhZmNlNi04ODI4LTQzMzItODY0Ny04M2Q1OWFmZDlkOTEiLCJnaXZlbl9uYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQGVzdG9yZS5jb20iLCJwZXJtaXNzaW9ucyI6IjAiLCJleHAiOjE3MDE3MDEzNjksImlzcyI6IkVTdG9yZS5BUEkiLCJhdWQiOiJFU3RvcmUuQVBJIn0.u-Sm0_5fx0Lsp1M-NikjbRfLwZUJOOjWmDnCB-rVbXc

###

POST {{host}}/api/login
Content-Type: {{contentType}}

{
  "email": "nr.ali1912@gmail.com",
  "password": "nawarali1912"
}